spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Flyway configuration
  flyway:
    enabled: true
    schemas: productdb
    baseline-on-migrate: true
    locations: classpath:db/migration
    encoding: UTF-8
    cleanDatabaseOnStartup: true

app:
  write:
    enabled: true


